version: '3.8'

name: acto-maps

services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: acto-postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - acto-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: acto-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - acto-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Mintlify (Documentation)
  mintlify:
    image: node:20-alpine
    container_name: acto-mintlify
    working_dir: /docs
    command: sh -c "npm install -g mintlify && mintlify dev --host 0.0.0.0"
    volumes:
      - ./docs:/docs
    ports:
      - "3000:3000"
    networks:
      - acto-network
    restart: unless-stopped

networks:
  acto-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
